### ISSUE TITLE
Cannot change pwm frequency on teensy 3.2

### ISSUE THREAD

**Issue by swapnilsayansaha** [PaulStoffregen/Tlc5940#16] opened 2020-07-31 23:14 UTC
Description

I connected a TLC5940NT from TI to a Teensy 3.2. While the LEDs light up, I observed that the PWM frequency is 977 Hz as expected by default. I tried changing the PWM frequency by modifying the TLC_config.h file, using the following guide as reference: https://www.oxgadgets.com/2011/10/using-tlc5940-to-generate-variable-frequency-pwm-signals-using-arduino.html.

As per the guide, to obtain 244 Hz PWM, I changed TLC_PWM_PERIOD to 32768 and TLC_GSCLK_PERIOD to 3. However, when observed with an oscilloscope, the PWM frequency is still 977 Hz.

I then set both the constants to 0, and still the PWM frequency was 977 Hz.

Does the library for teensy use the two constants from the config file at all? The math also does not add up, given Teensy 3.2 can run at 96 MHz and not 16 MHz.

**Comment by PaulStoffregen** [comment] 2020-08-09 14:14
Looks like this github issue is a duplicate of the same question you asked (and was answered) on the forum.

https://forum.pjrc.com/threads/62200-TLC5940-PWM-Frequency-does-not-alter-on-Teensy-3-2

Please do not create duplicate questions, at least not without linking to the other copies.  Duplicates only waste time for this sort of cleanup.

**Closed by PaulStoffregen** 2020-08-09 14:14 UTC
